spring.application.name=Envoy-backend

# ================================
# DATABASE CONFIGURATION
# ================================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/Envoy}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# ================================
# JPA / HIBERNATE
# ================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# ================================
# SERVER
# ================================
server.port=${PORT:8080}

# ================================
# JWT CONFIG
# ================================
envoy.jwt.secret=${ENVOY_JWT_SECRET}
envoy.jwt.expiration=3600000

# ================================
# AES ENCRYPTION
# ================================
envoy.encryption.key=${ENVOY_ENCRYPTION_KEY}

# ================================
# MAIL CONFIG
# ================================
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}

spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
